### ISSUE TITLE
Scroll bar issue

### ISSUE THREAD

**Issue by sumanrajpura** [anseki/jquery-ui-autocomplete-scroll#2]
Hello anseki,
I am using autocomplete as per your code.Issue I am facing is as below.
Once page is loaded you type a in input and auto complete results are shown.Now you scroll down through results till end and then click outside results that will close the auto complete results.now you delete a from input and once again type a in input you can see the scroll position of results is at bottom.
I want that it should be at top just like normal combo box input control.

**Comment by anseki** [comment]
Thank you @sumanrajpura! :smile:
I fixed it.

**Comment by sumanrajpura** [comment]
Thank you anseki.
